name: 'Gemini'
inputs:
  prompt: 
    description: 'Prompt para Gemini'
    required: true
    type: string
  output-artifact: 
    required: true
    type: string
  GH_TOKEN:
    required: true
    type: string
  GOOGLE_API_KEY:
    required: true
    type: string
  ATTEMPTS:
    required: true
    type: string

runs:
  using: "Composite"
  steps:

    - name: "Check attempts"
      if: ${{ inputs.ATTEMTPS >= 3 
      shell: bash
      run:  | 
        echo "YA NO QUEDAN INTENTOS DISPONIBLES..."
        exit 1
  
    - name: "Clone Gemini repository"
      shell: bash
      run: git clone https://${{ env.GH_TOKEN }}@github.com/Drastyn/gemini.git
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
        
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: "Install requirements"
      shell: bash
      run: pip install -r gemini/requirements.txt

    - name: "Prompt generation"
      shell: bash
      run: python3 gemini/main.py "${{ inputs.prompt }}"
      env:
        GOOGLE_API_KEY: ${{ inputs.GOOGLE_API_KEY }} 

    - name: "Upload prompt"
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.output-artifact }}
        path: ${{ github.workspace }}/output
        retention-days: 1
