name: 'Gemini'
inputs:
  concept: 
    description: 'Concepto para Gemini'
    required: true
    type: string
  style:
    description: 'Stylo del concepto'
    required: true
    type: string
  output-artifact: 
    required: true
    type: string
  output-file-name: 
    required: true
    type: string
  GH_TOKEN:
    required: true
    type: string
  GOOGLE_API_KEY:
    required: true
    type: string
  ATTEMPTS:
    required: true
    type: string

runs:
  using: "Composite"
  steps:
    - name: "Check attempts"
      shell: bash
      run:  |
        if [[ "${{ inputs.ATTEMPTS }}" -ge 3 ]]; then
          echo "YA NO QUEDAN INTENTOS DISPONIBLES..."
          exit 1
        fi
  
    - name: "Clone Gemini repository"
      shell: bash
      run: git clone https://${{ env.GH_TOKEN }}@github.com/Drastyn/gemini.git
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
        
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: "Install requirements"
      shell: bash
      run: pip install -r gemini/requirements.txt

    - name: "Prompt generation"
      shell: bash
      run: python3 gemini/main.py "${{ inputs.concept }}"
      env:
        GOOGLE_API_KEY: ${{ inputs.GOOGLE_API_KEY }} 
        OUTPUT_FILE_NAME: ${{ inputs.output-file-name }}

    - name: "Upload prompt"
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.output-artifact }}
        path: ${{ github.workspace }}/output
        retention-days: 1
